spring:
  datasource:
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000   #????30????????1800?
      connection-test-query: SELECT 1
    username: root
    password: example
    url: jdbc:mysql://127.0.0.1:3306/local_db?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8&useCursorFetch=true
    driver-class-name: com.mysql.cj.jdbc.Driver